all:
  children:
    swarm_manager:
      hosts:
        manager:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 44.193.72.112
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    swarm_workers:
      hosts:
        worker1:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 44.198.164.115
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        worker2:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 3.236.158.95
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

        worker3:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 18.209.93.123
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
#          ansible_ssh_private_key_file: ~/.ssh/id_rsa
# Direct host entries (if not using dynamic inventory)
# [swarm_manager]
#
#manager ansible_host=34.200.241.39 ansible_user=ec2-user
#worker1 ansible_host=44.201.20.232 ansible_user=ec2-user
#worker2 ansible_host=18.207.108.14 ansible_user=ec2-user
