all:
  children:
    swarm_manager:
      hosts:
        manager:
          ansible_host: 35.170.71.14
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ${{ secrets.SSH_PRIVATE_KEY }}
    swarm_workers:
      hosts:
        worker1:
          ansible_host: 34.201.35.72
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ${{ secrets.SSH_PRIVATE_KEY }}
        worker2:
          ansible_host: 44.192.112.155
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ${{ secrets.SSH_PRIVATE_KEY }}

        worker3:
          ansible_host: 18.205.1.72
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ${{ secrets.SSH_PRIVATE_KEY }}
#          ansible_ssh_private_key_file: ~/.ssh/id_rsa
# Direct host entries (if not using dynamic inventory)
# [swarm_manager]
#
#manager ansible_host=34.200.241.39 ansible_user=ec2-user
#worker1 ansible_host=44.201.20.232 ansible_user=ec2-user
#worker2 ansible_host=18.207.108.14 ansible_user=ec2-user
