all:
  children:
    swarm_manager:
      hosts:
        manager:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 3.239.42.195
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    swarm_workers:
      hosts:
        worker1:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 3.223.136.173
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        worker2:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 98.92.128.20
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

        worker3:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 98.92.149.73
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    monitoring:
      hosts:
        monitoring_server:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 44.200.13.249
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
