all:
  children:
    swarm_manager:
      hosts:
        manager:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 98.93.130.91
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    swarm_workers:
      hosts:
        worker1:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 52.90.239.194
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        worker2:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 100.30.173.13
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

#        worker3:
#          ansible_python_interpreter: /usr/bin/python3
#          ansible_host: 54.90.244.240
#          ansible_user: ubuntu
#          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    monitoring:
      hosts:
        monitoring_server:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 3.231.227.198
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
