all:
  children:
    swarm_manager:
      hosts:
        manager:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 52.90.49.53
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    swarm_workers:
      hosts:
        worker1:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 54.226.80.0
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        worker2:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 54.90.190.176
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

        worker3:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 54.90.244.240
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    monitoring:
      hosts:
        monitoring_server:
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: 54.172.168.178
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
