all:
  children:
    swarm_manager:
      hosts:
        manager:
          ansible_host: 34.200.241.39
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    swarm_workers:
      hosts:
        worker1:
          ansible_host: 44.201.20.232
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        worker2:
          ansible_host: 18.207.108.14
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
#          ansible_ssh_private_key_file: ~/.ssh/id_rsa
